/**
 * Git worktree lifecycle for isolated agent runs.
 */

import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import process from "node:process";

import { summarizeSceneResourceChange } from "./engine-runtime.mjs";
import { ensureGitRepository, git, gitChecked } from "./git.mjs";

/**
 * Artifacts produced by RUNNING a project, never by editing it.
 *
 * Deliberately excludes anything ambiguous: `dist/` and `build/` are committed
 * deliberately by plenty of projects, so they are not listed. Same reasoning
 * keeps Godot's `android/build/` out - the installed Android build template is
 * routinely hand-customized, so it is source in every project that has it.
 */
const GENERATED_ARTIFACT_PATTERNS = Object.freeze([
  "__pycache__/",
  "*.py[cod]",
  ".pytest_cache/",
  ".mypy_cache/",
  ".ruff_cache/",
  ".tox/",
  "__pypackages__/",
  "*.egg-info/",
  "node_modules/",
  "target/",
  "obj/",
  ".gradle/",
  "*.tsbuildinfo",
  // Godot: .import is Godot 3's asset import CACHE DIRECTORY; .godot is Godot
  // 4's. Neither is source - both are regenerated from project assets.
  //
  // These are DIRECTORY patterns on purpose. Never "harmonize" `.import/` into
  // `*.import`, and never add `*.uid`: `icon.png.import` and `player.gd.uid`
  // are SOURCE. They carry the `uid://...` identifier that every `.tscn`/
  // `.tres` `ext_resource uid=` line resolves through, so dropping them from a
  // commit breaks resource references across the whole project. Godot 4.4 does
  // regenerate a missing `.uid` - with a NEW RANDOM uid - which is exactly why
  // "it regenerates" is the wrong reason to exclude it.
  ".import/",
  ".godot/",
  // Godot 3 emitted C# build output into `.mono/` at the project root; Godot
  // 4's equivalent lives under `.godot/mono` and is already covered above.
  ".mono/",
  // Blender: incremental save backups. `scene.blend1` is the previous save,
  // and Save Versions goes up to 32, so both a one- and two-digit form are
  // needed. `.blend@` is NOT a backup - it is the transient write target
  // Blender renames over the real file on a successful save, so it only ever
  // survives a crashed or interrupted save. Deliberately does NOT list
  // `*.blend` itself: the scene file is the source of a Blender project.
  "*.blend[0-9]",
  "*.blend[0-9][0-9]",
  "*.blend@",
  "*.blend[0-9]@",
  // JS/web framework build caches - regenerated by the framework's own
  // dev/build command, never meant to be committed. Unlike a generic
  // dist/build folder name (which some projects DO commit deliberately, so
  // is intentionally not listed here), these framework-specific directory
  // names are unambiguous build output in every project that has them.
  ".next/",
  ".nuxt/",
  ".svelte-kit/",
  ".turbo/",
  ".parcel-cache/",
  // The run's own scratch directory inside the worktree (provision.mjs's
  // WORKTREE_SCRATCH_DIR). Nothing under it is the user's work. It matters most
  // for --blender-sandbox, whose junction points at a directory that is itself
  // inside the worktree: on win32 git walks a junction as an ordinary directory,
  // so without this the commit would carry a duplicate copy of the whole add-on
  // (measured - removing this entry stages
  // `.grok-build/blender/scripts/addons/myaddon/__init__.py`).
  //
  // A directory pattern, and only a directory pattern: the project config file
  // `.grok-build.json` is a SIBLING with a longer name, it is normal tracked
  // source, and `**/.grok-build` never matches it.
  ".grok-build/",
  // Per-run runtime plugin injection lands under `.grok/plugins/turbo-build-runtime/`
  // (provision.mjs injectRuntimePlugin). Hyper discovers project plugins from
  // `.grok/plugins/*/`, so the pack has to live there for the agent to see it —
  // and must NEVER be committed as the user's work. Same directory-pattern
  // form as `.grok-build/`: the project config is `.grok-build.json` (different
  // name), and a future user-authored `.grok/config.toml` would be a sibling
  // of `plugins/` that we also do not want staged from a run worktree.
  ".grok/"
]);

/**
 * Machine-local secrets that must never reach a commit, even though they are
 * not "generated artifacts" in the sense above.
 *
 * Kept as a separate constant precisely so the next reader does not "clean up"
 * an odd credentials entry sitting among build caches.
 *
 * `export_credentials.cfg` is Godot 4.2+: the editor moved keystore passwords
 * and notarization credentials out of `export_presets.cfg` into this sibling
 * file, which is machine-local by design. A headless `--export-release` run
 * can generate it inside the worktree, so it has to be excluded even though
 * `git worktree add` would never have materialised one.
 *
 * `export_presets.cfg` itself is deliberately NOT listed: it is normal,
 * already-tracked project source in the user's repository.
 */
/**
 * Secrets and untracked runtime files that provision.mjs may copy into a
 * worktree so verify can run (`.env`, registry auth, local Django settings).
 * They must never be committed onto a run branch — land would otherwise push
 * machine-local credentials into the user's real history.
 *
 * Keep in sync with PROVISION_COPY_FILES in provision.mjs (the commit gate is
 * pathspec-based and cannot import that module without a cycle risk through
 * git helpers, so the names are duplicated deliberately).
 */
const NEVER_COMMIT_PATTERNS = Object.freeze([
  "export_credentials.cfg",
  ".env",
  ".env.local",
  ".env.development",
  ".env.test",
  ".npmrc",
  ".yarnrc.yml",
  "local_settings.py",
  "settings_local.py",
  "secrets.json"
]);

/**
 * Unaccounted debris the agent left behind — not committed work, not a
 * recognised build cache. Field-report BRIDGE-12: Sol left
 * `build_wreck_headless.log` / `verify_wreck_gate.log` at the repo root and
 * the bridge classed them as "excluded artifacts", so they were invisible.
 * These stay on disk and stay out of the commit; they are only reported.
 */
const DEBRIS_BASENAME_PATTERNS = Object.freeze([
  /^.*\.log$/i,
  /^.*\.tmp$/i,
  /^.*\.temp$/i,
  /^.*\.swp$/i,
  /^.*\.swo$/i,
  /^core$/i,
  /^core\.\d+$/i,
  /^.*\.dmp$/i,
  /^.*\.stackdump$/i,
  /^hs_err_pid\d+\.log$/i,
  /^npm-debug\.log.*$/i,
  /^yarn-error\.log$/i
]);

/**
 * Convert a GENERATED_ARTIFACT_PATTERNS entry into a path matcher.
 * Directory patterns end with `/`; file globs use `*`.
 *
 * @param {string} pattern
 * @returns {(relPath: string) => boolean}
 */
function compileArtifactPattern(pattern) {
  const raw = String(pattern ?? "");
  if (raw.endsWith("/")) {
    const dir = raw.slice(0, -1).replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*/g, "[^/]*");
    const re = new RegExp(`(?:^|/)${dir}(?:/|$)`);
    return (relPath) => re.test(String(relPath).replace(/\\/g, "/"));
  }
  const body = raw.replace(/[.+^${}()|[\]\\]/g, "\\$&").replace(/\*/g, "[^/]*");
  const re = new RegExp(`(?:^|/)${body}$`);
  return (relPath) => re.test(String(relPath).replace(/\\/g, "/"));
}

const GENERATED_ARTIFACT_MATCHERS = GENERATED_ARTIFACT_PATTERNS.map(compileArtifactPattern);
const NEVER_COMMIT_MATCHERS = NEVER_COMMIT_PATTERNS.map(compileArtifactPattern);

/**
 * True when a repository-relative path is a recognised generated build cache
 * (or a never-commit secret), i.e. correctly excluded from the commit.
 *
 * @param {string} relPath
 * @returns {boolean}
 */
export function isGeneratedArtifactPath(relPath) {
  const normalized = String(relPath ?? "").replace(/\\/g, "/").replace(/^\.\//, "");
  if (!normalized) {
    return false;
  }
  return (
    GENERATED_ARTIFACT_MATCHERS.some((match) => match(normalized)) ||
    NEVER_COMMIT_MATCHERS.some((match) => match(normalized))
  );
}

/**
 * True when a path looks like unaccounted debris (loose logs, temps, dumps)
 * rather than intentional source or a known cache. Root-level `*.log` is the
 * field-report case; nested temps count too.
 *
 * @param {string} relPath
 * @returns {boolean}
 */
export function isDebrisPath(relPath) {
  const normalized = String(relPath ?? "").replace(/\\/g, "/").replace(/^\.\//, "");
  if (!normalized || isGeneratedArtifactPath(normalized)) {
    return false;
  }
  const base = normalized.includes("/") ? normalized.slice(normalized.lastIndexOf("/") + 1) : normalized;
  return DEBRIS_BASENAME_PATTERNS.some((re) => re.test(base));
}

/**
 * Split status entries (`<letter>\\t<path>`) into real work vs debris.
 * Generated artifacts should already have been filtered by the caller; if any
 * remain they are dropped rather than counted as either side.
 *
 * @param {string[]} entries
 * @returns {{ work: string[], debris: string[] }}
 */
export function partitionWorkAndDebris(entries) {
  const work = [];
  const debris = [];
  for (const entry of Array.isArray(entries) ? entries : []) {
    const tab = String(entry).indexOf("\t");
    const rel = tab >= 0 ? String(entry).slice(tab + 1).trim() : String(entry).trim();
    // Annotation suffix " (scene edit)" etc. — strip for classification.
    const pathOnly = rel.replace(/\s+\(.*\)$/, "");
    if (!pathOnly || isGeneratedArtifactPath(pathOnly)) {
      continue;
    }
    if (isDebrisPath(pathOnly)) {
      debris.push(entry);
    } else {
      work.push(entry);
    }
  }
  return { work, debris };
}

export { GENERATED_ARTIFACT_PATTERNS, NEVER_COMMIT_PATTERNS };

/**
 * Stable 8-character digest of a run id for short Windows worktree paths.
 *
 * Deep engine caches (`.godot/imported/…`) under a long plugin-data prefix
 * blow past MAX_PATH; `git worktree remove` then fails with "Filename too long"
 * and leaves multi-hundred-MB orphans. The short form keeps the absolute path
 * under the limit without changing how land/prune find an existing worktree —
 * those always use the path stored on the job record, never recompute it.
 *
 * @param {string} runId
 * @returns {string}
 */
export function shortWorktreeId(runId) {
  return crypto.createHash("sha256").update(String(runId ?? "")).digest("hex").slice(0, 8);
}

/** Env override for the directory that holds short-id worktree children. */
export const WORKTREE_ROOT_ENV = "GROK_BUILD_WORKTREE_ROOT";

/**
 * Directory under which NEW worktrees are created (parent of the run id entry).
 *
 * Precedence:
 *   1. explicit `dataDir` → `${dataDir}/worktrees` (tests own the layout)
 *   2. `GROK_BUILD_WORKTREE_ROOT` env override
 *   3. same volume as `repoRoot` when known (`{volume}/gb/w` on win32, or
 *      `{tmpdir}/gb/w` on POSIX) so hardlink seeding works and private cargo
 *      target dirs do not fill a different drive
 *   4. historical fallbacks (TEMP / CLAUDE_PLUGIN_DATA / tmpdir)
 *
 * Windows constraints (do not regress these):
 *   - Junctions under bare `%LOCALAPPDATA%\…` (outside Temp) resolve as ENOENT
 *     on this host class even though `mklink` succeeds — never default there.
 *   - Paths must stay short enough that deep `.godot/imported/…` trees clear
 *     MAX_PATH; an 8-char digest under `{volume}\gb\w\` does.
 *
 * Existing worktrees recorded under an older root must still be found, removed
 * and landed — resolve those from the stored job descriptor, never by calling
 * this function again.
 *
 * @param {{ dataDir?: string, env?: NodeJS.ProcessEnv, platform?: string, repoRoot?: string }} [options]
 * @returns {string}
 */
export function resolveWorktreeRoot(options = {}) {
  const env = options.env ?? process.env;
  if (options.dataDir) {
    return path.join(options.dataDir, "worktrees");
  }
  const override = env?.[WORKTREE_ROOT_ENV];
  if (override != null && String(override).trim()) {
    return path.resolve(String(override).trim());
  }

  const platform = options.platform ?? process.platform;
  const repoRoot =
    options.repoRoot != null && String(options.repoRoot).trim()
      ? path.resolve(String(options.repoRoot).trim())
      : null;

  if (platform === "win32") {
    // Prefer the repository's own volume so hardlinks seed node_modules/.godot
    // and a private CARGO_TARGET_DIR cannot fill C: while the repo lives on H:.
    // Layout `{volume}\gb\w\<8-char>` is short enough for MAX_PATH and is not
    // bare LOCALAPPDATA (junctions fail to resolve there on this host class).
    if (repoRoot) {
      const volumeRoot = path.parse(repoRoot).root || path.parse(repoRoot).dir;
      return path.join(volumeRoot, "gb", "w");
    }
    // No repo root yet: short TEMP path (historical). Junctions under TEMP work.
    const tempRoot = env.TEMP || env.TMP || os.tmpdir();
    return path.join(tempRoot, "gb", "w");
  }

  // POSIX: same-volume preference when we know the repo; otherwise historical.
  if (repoRoot) {
    return path.join(os.tmpdir(), "gb", "w");
  }
  if (env.CLAUDE_PLUGIN_DATA) {
    return path.join(env.CLAUDE_PLUGIN_DATA, "worktrees");
  }
  return path.join(os.tmpdir(), "grok-cc-worktrees");
}

/**
 * Where a NEW worktree for `runId` should be created.
 *
 * Honour an explicit `dataDir` (tests and callers that own the layout). Prefer
 * the same volume as the repository when known — see `resolveWorktreeRoot`.
 *
 * Existing worktrees recorded under the old path must still be found, removed
 * and landed — resolve those from the stored job descriptor, never by calling
 * this function again.
 *
 * @param {string} runId
 * @param {{ dataDir?: string, env?: NodeJS.ProcessEnv, platform?: string, repoRoot?: string }} [options]
 */
export function resolveWorktreePath(runId, options = {}) {
  const env = options.env ?? process.env;
  if (options.dataDir) {
    // Tests keep the full run id so paths stay readable in fixtures.
    return path.join(options.dataDir, "worktrees", runId);
  }
  const root = resolveWorktreeRoot({ ...options, env });
  const platform = options.platform ?? process.platform;
  // Short digest under gb/w (win32 default, GROK_BUILD_WORKTREE_ROOT, or the
  // same-volume default). Full run id under the historical CLAUDE_PLUGIN_DATA
  // / grok-cc-worktrees layouts so older operators and docs still match.
  const usesShortId =
    platform === "win32" ||
    Boolean(env?.[WORKTREE_ROOT_ENV] && String(env[WORKTREE_ROOT_ENV]).trim()) ||
    path.basename(root) === "w";
  if (usesShortId) {
    return path.join(root, shortWorktreeId(runId));
  }
  return path.join(root, runId);
}

/**
 * win32 long-path form (`\\?\C:\…`). Only meaningful on Windows; elsewhere
 * returns the resolved path unchanged. Used when ordinary recursive delete
 * fails with "Filename too long".
 *
 * @param {string} targetPath
 * @returns {string}
 */
export function toWin32LongPath(targetPath) {
  const resolved = path.resolve(String(targetPath ?? ""));
  if (process.platform !== "win32") {
    return resolved;
  }
  if (resolved.startsWith("\\\\?\\")) {
    return resolved;
  }
  // UNC paths need \\?\UNC\server\share, not \\?\server\share.
  if (resolved.startsWith("\\\\")) {
    return `\\\\?\\UNC\\${resolved.slice(2)}`;
  }
  return `\\\\?\\${resolved}`;
}

/**
 * Free space a worktree checkout is required to have available before git is
 * allowed to start writing one.
 *
 * Base floor is deliberately flat rather than a per-repo tree walk: summing
 * `git ls-tree -r --long HEAD` undercounts LFS and is itself expensive on the
 * repos that need the warning. Ecosystem floors raise the bar when the run is
 * expected to build (Rust cargo target dirs alone have measured multi-GB).
 * Override with GROK_BUILD_MIN_FREE_BYTES (0 disables).
 */
const MIN_WORKTREE_FREE_BYTES = 512 * 1024 * 1024;
const MIN_WORKTREE_FREE_BYTES_ENV = "GROK_BUILD_MIN_FREE_BYTES";

/** Per-ecosystem free-space floors (bytes). Highest matching ecosystem wins. */
export const ECOSYSTEM_MIN_FREE_BYTES = Object.freeze({
  rust: 2 * 1024 * 1024 * 1024,
  godot: 1024 * 1024 * 1024,
  blender: 1024 * 1024 * 1024,
  node: 512 * 1024 * 1024,
  python: 512 * 1024 * 1024
});

export function formatBytes(bytes) {
  const value = Number(bytes);
  if (!Number.isFinite(value) || value < 0) {
    return "unknown";
  }
  const units = ["B", "KB", "MB", "GB", "TB"];
  let index = 0;
  let scaled = value;
  while (scaled >= 1024 && index < units.length - 1) {
    scaled /= 1024;
    index += 1;
  }
  return `${index === 0 ? scaled : scaled.toFixed(1)} ${units[index]}`;
}

/**
 * Resolve the free-space floor for a worktree create.
 *
 * @param {NodeJS.ProcessEnv} [env]
 * @param {{ ecosystems?: Array<string|{id?: string}>, minFreeBytes?: number }} [options]
 * @returns {number}
 */
export function resolveMinFreeBytes(env, options = {}) {
  if (Number.isFinite(options.minFreeBytes) && options.minFreeBytes >= 0) {
    return Math.floor(options.minFreeBytes);
  }
  const raw = Number(env?.[MIN_WORKTREE_FREE_BYTES_ENV]);
  if (Number.isFinite(raw) && raw >= 0) {
    return Math.floor(raw);
  }
  let floor = MIN_WORKTREE_FREE_BYTES;
  const ecosystems = Array.isArray(options.ecosystems) ? options.ecosystems : [];
  for (const entry of ecosystems) {
    const id = typeof entry === "string" ? entry : entry?.id;
    const needed = id ? ECOSYSTEM_MIN_FREE_BYTES[id] : null;
    if (Number.isFinite(needed) && needed > floor) {
      floor = needed;
    }
  }
  return floor;
}

/**
 * Throw before `git worktree add` if the target volume is out of room.
 *
 * Never throws for its own failure: `statfsSync` is unsupported on some remote
 * and virtualised filesystems, and refusing to run there would be a far worse
 * regression than the opaque git error this replaces. An unreadable volume
 * simply skips the check.
 *
 * @param {string} parentDir directory the worktree will be created inside
 * @param {(dir: string) => {bsize: number, bavail: number}} statfsImpl
 * @param {NodeJS.ProcessEnv} env
 * @param {{ ecosystems?: Array<string|{id?: string}>, minFreeBytes?: number }} [options]
 */
function assertFreeSpaceForWorktree(parentDir, statfsImpl, env, options = {}) {
  const required = resolveMinFreeBytes(env, options);
  if (required <= 0) {
    return;
  }

  let stats;
  try {
    stats = statfsImpl(parentDir);
  } catch {
    return;
  }

  const blockSize = Number(stats?.bsize);
  const availableBlocks = Number(stats?.bavail);
  if (!Number.isFinite(blockSize) || !Number.isFinite(availableBlocks)) {
    return;
  }

  const available = blockSize * availableBlocks;
  if (available >= required) {
    return;
  }

  // `path.parse().root` is the drive on win32 ("H:\\") and "/" on POSIX -
  // the unit the user actually has to free space on, not the temp subdir.
  const volume = path.parse(path.resolve(parentDir)).root || parentDir;
  throw new Error(
    `Not enough free space on ${volume} to create a worktree: need ~${formatBytes(required)}, have ${formatBytes(available)}. ` +
      `Free some space, or run without isolation (--no-isolate).`
  );
}

/**
 * Create a worktree for a run.
 *
 * `statfsImpl`/`gitImpl` exist so the free-space precheck can be tested without
 * a full disk. They are seams, not configuration: production passes neither.
 *
 * Nested delegation (nest.mjs) MUST pass `worktreePath` derived via
 * `deriveSiblingWorktreePath` whenever a parent worktree exists. A worktree
 * inside a worktree breaks `git worktree remove`, doubles path length on
 * Windows, and makes the artifact excludes and `land` graph incoherent —
 * sibling directories only, never nested.
 *
 * @param {object} options
 * @param {string} options.cwd - source repository cwd
 * @param {string} options.runId
 * @param {string} [options.baseRef] - defaults to HEAD
 * @param {string} [options.dataDir]
 * @param {string} [options.worktreePath] - explicit path (sibling placement)
 * @param {NodeJS.ProcessEnv} [options.env]
 * @param {Array<string|{id?: string}>} [options.ecosystems] - raise free-space floor
 * @param {number} [options.minFreeBytes] - explicit free-space floor override
 * @param {typeof fs.statfsSync} [options.statfsImpl]
 * @param {typeof git} [options.gitImpl]
 */
export function createWorktree({
  cwd,
  runId,
  baseRef = "HEAD",
  dataDir,
  worktreePath: worktreePathOverride,
  env,
  ecosystems,
  minFreeBytes,
  statfsImpl = fs.statfsSync,
  gitImpl = git
}) {
  const repoRoot = ensureGitRepository(cwd);
  if (!runId) {
    throw new Error("runId is required");
  }

  const branchName = `turbo-build/${runId}`;
  const worktreePath = worktreePathOverride
    ? path.resolve(String(worktreePathOverride))
    : resolveWorktreePath(runId, { dataDir, env, repoRoot });
  const baseSha = gitChecked(repoRoot, ["rev-parse", baseRef]).stdout.trim();

  fs.mkdirSync(path.dirname(worktreePath), { recursive: true });

  if (fs.existsSync(worktreePath)) {
    throw new Error(`Worktree path already exists: ${worktreePath}`);
  }

  // After the mkdir so the directory being measured exists, and before the
  // first git write so a full disk costs a clear message instead of a partial
  // checkout plus `Failed to create worktree: <git stderr>`.
  assertFreeSpaceForWorktree(path.dirname(worktreePath), statfsImpl, env ?? process.env, {
    ecosystems,
    minFreeBytes
  });

  const result = gitImpl(repoRoot, ["worktree", "add", "-b", branchName, worktreePath, baseSha]);
  if (result.status !== 0) {
    // Branch may already exist from a crashed run — try without -b
    const retry = gitImpl(repoRoot, ["worktree", "add", worktreePath, branchName]);
    if (retry.status !== 0) {
      const combined = [result.stderr, result.stdout, retry.stderr, retry.stdout]
        .map((s) => (s || "").trim())
        .filter(Boolean)
        .join("\n");
      throw new Error(`Failed to create worktree: ${combined}`);
    }
  }

  // Best-effort: deep engine caches under the worktree otherwise hit MAX_PATH
  // on win32 during teardown. Unsupported git versions simply ignore the set.
  try {
    gitImpl(worktreePath, ["config", "core.longpaths", "true"]);
  } catch {
    // creation already succeeded; longpaths is a teardown aid, not a gate
  }

  return {
    worktreePath,
    branchName,
    baseSha,
    baseRef,
    repoRoot,
    runId
  };
}

/**
 * Remove a worktree and optionally its branch.
 *
 * @param {object} options
 * @param {string} options.repoRoot
 * @param {string} options.worktreePath
 * @param {string} [options.branchName]
 * @param {boolean} [options.deleteBranch]
 */
/**
 * Remove every symlink/junction inside a worktree, WITHOUT descending into one.
 *
 * Confirmed empirically: `git worktree remove --force` on Windows follows a
 * junction it encounters while deleting the tree and destroys the CONTENTS of
 * whatever it points at. lib/provision.mjs still junctions *read-mostly* dirs
 * (e.g. vendor/) from the user's real repository, and Blender sandbox links
 * live inside the worktree — so tearing down a worktree that still contains
 * those links wiped the real directories in a reproduction (empty
 * node_modules/ survived; node_modules/pkg/marker.txt inside it did not).
 * Live-state dirs (node_modules, .venv, target, …) are private copies now,
 * but the unlink-first order remains mandatory for every remaining reparse
 * point.
 *
 * The only safe order is: unlink every reparse point first, so by the time git
 * (or the fs.rmSync fallback below) walks the tree, there is nothing left to
 * follow through. This must run before ANY removal path, not only the fallback.
 */
function unlinkReparsePointsSync(root) {
  let entries;
  try {
    entries = fs.readdirSync(root, { withFileTypes: true });
  } catch {
    return;
  }

  for (const entry of entries) {
    const entryPath = path.join(root, entry.name);
    if (entry.isSymbolicLink()) {
      // Covers POSIX symlinks and Windows junctions (Node reports junctions as
      // symbolic links via lstat/Dirent). rmdir removes a Windows junction or a
      // directory-targeted symlink without touching its target; unlink handles
      // a file-targeted symlink. Never rmSync/recursive here — that is exactly
      // the operation this function exists to protect against.
      try {
        fs.rmdirSync(entryPath);
      } catch {
        try {
          fs.unlinkSync(entryPath);
        } catch {
          // Leaving an un-removable link is safer than risking a recursive
          // delete following it later; the outer removal may then fail loudly
          // instead of silently destroying the link target.
        }
      }
      continue;
    }
    if (entry.isDirectory()) {
      unlinkReparsePointsSync(entryPath);
    }
  }
}

/**
 * Attempt to delete a directory tree, including the win32 `\\?\` long-path
 * form when ordinary recursive delete fails (deep `.godot/imported/…` trees).
 *
 * @param {string} targetPath
 * @param {{ platform?: string, rmSyncImpl?: typeof fs.rmSync }} [options]
 * @returns {{ deleted: boolean, errorText?: string }}
 */
export function removeDirectoryTree(targetPath, options = {}) {
  if (!targetPath) {
    return { deleted: true };
  }
  const platform = options.platform ?? process.platform;
  const rmSyncImpl = options.rmSyncImpl ?? fs.rmSync.bind(fs);
  const exists = options.existsImpl ?? ((p) => fs.existsSync(p));

  if (!exists(targetPath)) {
    return { deleted: true };
  }

  let lastError = null;
  try {
    rmSyncImpl(targetPath, { recursive: true, force: true });
  } catch (error) {
    lastError = error;
  }

  if (!exists(targetPath)) {
    return { deleted: true };
  }

  // win32 only: retry through the extended-length path. Node's fs accepts
  // `\\?\` prefixes; without them MAX_PATH still applies and deep Godot caches
  // survive every ordinary delete.
  if (platform === "win32") {
    try {
      rmSyncImpl(toWin32LongPath(targetPath), { recursive: true, force: true });
    } catch (error) {
      lastError = error;
    }
  }

  if (!exists(targetPath)) {
    return { deleted: true };
  }

  return {
    deleted: false,
    errorText: lastError instanceof Error ? lastError.message : lastError ? String(lastError) : "directory still exists"
  };
}

/**
 * Best-effort recursive byte size of a directory tree (follows neither
 * junctions nor symlinks — only real files). Used to report private cargo
 * target / scratch dirs before teardown.
 *
 * @param {string} targetPath
 * @param {{ maxEntries?: number }} [options]
 * @returns {{ bytes: number, truncated: boolean }}
 */
export function measureDirectorySize(targetPath, options = {}) {
  const maxEntries = Number.isFinite(options.maxEntries) ? options.maxEntries : 50_000;
  let bytes = 0;
  let entries = 0;
  let truncated = false;

  const walk = (dir) => {
    if (truncated) {
      return;
    }
    let listing;
    try {
      listing = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of listing) {
      if (truncated) {
        return;
      }
      entries += 1;
      if (entries > maxEntries) {
        truncated = true;
        return;
      }
      const full = path.join(dir, entry.name);
      // Do not follow reparse points — measuring through a junction into the
      // user's real node_modules would inflate the number and risk walking off
      // the worktree entirely.
      if (entry.isSymbolicLink()) {
        continue;
      }
      if (entry.isDirectory()) {
        walk(full);
        continue;
      }
      if (entry.isFile()) {
        try {
          bytes += fs.statSync(full).size;
        } catch {
          // skip unreadable
        }
      }
    }
  };

  if (targetPath && fs.existsSync(targetPath)) {
    walk(targetPath);
  }
  return { bytes, truncated };
}

/**
 * Relative path of the per-worktree private cargo target (mirrors provision.mjs
 * CARGO_TARGET_DIR_RELATIVE without importing that module — cycle risk).
 */
const PRIVATE_CARGO_TARGET_RELATIVE = path.join(".grok-build", "cargo-target");

/**
 * Measure the private CARGO_TARGET_DIR inside a worktree before removal.
 * Returns null when the directory is absent.
 *
 * @param {string} worktreePath
 * @returns {{ path: string, bytes: number, truncated: boolean, label: string }|null}
 */
export function measurePrivateTargetDir(worktreePath) {
  if (!worktreePath) {
    return null;
  }
  const targetPath = path.join(worktreePath, PRIVATE_CARGO_TARGET_RELATIVE);
  if (!fs.existsSync(targetPath)) {
    return null;
  }
  const measured = measureDirectorySize(targetPath);
  return {
    path: targetPath,
    bytes: measured.bytes,
    truncated: measured.truncated,
    label: `private cargo target ${formatBytes(measured.bytes)}${measured.truncated ? " (partial)" : ""}`
  };
}

export function removeWorktree({
  repoRoot,
  worktreePath,
  branchName,
  deleteBranch = true,
  platform = process.platform,
  rmSyncImpl,
  existsImpl
}) {
  const exists = existsImpl ?? ((p) => fs.existsSync(p));
  let removeError = null;
  // Report private target size before teardown so operators can see why a
  // volume filled (field: 7.5 GB CARGO_TARGET_DIR on the wrong drive).
  const privateTarget = measurePrivateTargetDir(worktreePath);

  if (worktreePath && exists(worktreePath)) {
    unlinkReparsePointsSync(worktreePath);
    const result = git(repoRoot, ["worktree", "remove", "--force", worktreePath]);
    if (result.status !== 0 || exists(worktreePath)) {
      const treeResult = removeDirectoryTree(worktreePath, { platform, rmSyncImpl, existsImpl: exists });
      if (!treeResult.deleted) {
        removeError = treeResult.errorText;
      }
      // Only prune the registration after we either deleted the directory or
      // have already failed loudly. Quiet prune-without-delete is what left
      // multi-hundred-MB orphans in the field while git forgot the worktree.
      git(repoRoot, ["worktree", "prune"]);
    }
  } else {
    git(repoRoot, ["worktree", "prune"]);
  }

  if (deleteBranch && branchName) {
    git(repoRoot, ["branch", "-D", branchName]);
  }

  const reasons = [];
  const stillOnDisk = Boolean(worktreePath && exists(worktreePath));
  if (stillOnDisk) {
    reasons.push(
      removeError
        ? `worktree directory still exists after removal attempt: ${removeError}`
        : "worktree directory still exists after removal attempt"
    );
  }
  if (deleteBranch && branchName) {
    const branchCheck = git(repoRoot, ["rev-parse", "--verify", branchName]);
    if (branchCheck.status === 0) {
      reasons.push(`branch ${branchName} still exists after delete attempt`);
    }
  }

  if (reasons.length > 0) {
    return {
      removed: false,
      worktreePath,
      branchName,
      reason: reasons.join("; "),
      // Loud rather than quietly deregistered: the caller (prune, land) must
      // list anything it could not delete so an operator can free the disk.
      orphanedPath: stillOnDisk ? worktreePath : null,
      privateTarget
    };
  }

  return { removed: true, worktreePath, branchName, orphanedPath: null, privateTarget };
}

/**
 * Walk a worktree root and report directories that have no corresponding job
 * record (and are not registered with `git worktree list`).
 *
 * Used by prune to surface the unbounded orphan accumulation measured in the
 * field (hundreds of directories under the shared root while git only knew
 * about a handful). Never force-deletes: the caller applies work-preservation
 * rules (uncommitted work stays).
 *
 * @param {object} options
 * @param {string} options.worktreeRoot - directory whose immediate children are candidates
 * @param {Iterable<string>|string[]} [options.knownPaths] - job-record worktree paths
 * @param {string} [options.repoRoot] - for git worktree list cross-check
 * @param {typeof git} [options.gitImpl]
 * @param {typeof fs.readdirSync} [options.readdirSyncImpl]
 * @param {typeof fs.existsSync} [options.existsSyncImpl]
 * @returns {{ orphans: Array<{ path: string, hasUncommittedWork: boolean, detail: string }>, root: string, scanned: number }}
 */
export function reconcileOrphanWorktrees({
  worktreeRoot,
  knownPaths = [],
  repoRoot = null,
  gitImpl = git,
  readdirSyncImpl = fs.readdirSync.bind(fs),
  existsSyncImpl = fs.existsSync.bind(fs)
}) {
  const root = worktreeRoot ? path.resolve(String(worktreeRoot)) : "";
  if (!root || !existsSyncImpl(root)) {
    return { orphans: [], root, scanned: 0 };
  }

  const known = new Set();
  for (const entry of knownPaths) {
    if (entry == null || !String(entry).trim()) {
      continue;
    }
    try {
      known.add(path.resolve(String(entry)));
    } catch {
      known.add(String(entry));
    }
  }

  // git worktree list --porcelain: "worktree <path>" lines are registered trees.
  if (repoRoot) {
    const listed = gitImpl(repoRoot, ["worktree", "list", "--porcelain"]);
    if (listed.status === 0) {
      for (const line of String(listed.stdout ?? "").split(/\r?\n/)) {
        if (line.startsWith("worktree ")) {
          const wt = line.slice("worktree ".length).trim();
          if (wt) {
            try {
              known.add(path.resolve(wt));
            } catch {
              known.add(wt);
            }
          }
        }
      }
    }
  }

  let children;
  try {
    children = readdirSyncImpl(root, { withFileTypes: true });
  } catch {
    return { orphans: [], root, scanned: 0 };
  }

  const orphans = [];
  let scanned = 0;
  for (const entry of children) {
    if (!entry.isDirectory() && !entry.isSymbolicLink()) {
      continue;
    }
    const childPath = path.join(root, entry.name);
    scanned += 1;
    let resolved = childPath;
    try {
      resolved = path.resolve(childPath);
    } catch {
      // keep childPath
    }
    if (known.has(resolved)) {
      continue;
    }
    // Also match by basename when known paths used a different root (legacy
    // TEMP vs volume root): a job that still points at the live directory
    // should not be reported as orphan.
    const base = entry.name;
    let matchedByName = false;
    for (const k of known) {
      if (path.basename(k) === base) {
        matchedByName = true;
        break;
      }
    }
    if (matchedByName) {
      continue;
    }

    const hasUncommittedWork = worktreeHasUncommittedWorkSafe(childPath, gitImpl);
    orphans.push({
      path: childPath,
      hasUncommittedWork,
      detail: hasUncommittedWork
        ? `Orphan worktree at ${childPath} has uncommitted work; not safe to auto-delete.`
        : `Orphan worktree directory at ${childPath} has no job record.`
    });
  }

  return { orphans, root, scanned };
}

/**
 * Best-effort uncommitted-work check that never throws (orphan scan must not
 * fail the whole prune plan because one directory is unreadable).
 *
 * @param {string} worktreePath
 * @param {typeof git} [gitImpl]
 * @returns {boolean}
 */
function worktreeHasUncommittedWorkSafe(worktreePath, gitImpl = git) {
  try {
    const status = gitImpl(worktreePath, [
      "status",
      "--porcelain",
      "--untracked-files=all",
      "--",
      ".",
      ...artifactExcludePathspecs()
    ]);
    if (status.status !== 0) {
      const fallback = gitImpl(worktreePath, ["status", "--porcelain", "--untracked-files=all"]);
      if (fallback.status !== 0) {
        // Unknown state: treat as protected so we never force-delete real work.
        return true;
      }
      return Boolean(String(fallback.stdout ?? "").trim());
    }
    return Boolean(String(status.stdout ?? "").trim());
  } catch {
    return true;
  }
}

/**
 * Pathspecs that stage everything except generated artifacts.
 *
 * Pathspec magic is used instead of info/exclude: in a linked worktree git
 * reads excludes from the common git dir, so per-worktree exclude files are
 * ignored. Pathspecs apply to one `git add` and write nothing into repo metadata.
 *
 * A directory pattern needs BOTH forms: the bare one and the recursive one.
 * The recursive form requires a path component AFTER `.godot`, so it never
 * matches an index entry whose path is exactly `.godot` - which is what git
 * records for that entry when it is a symlink rather than a directory. On
 * win32 the provisioned `.godot` is a junction and
 * git sees a directory, so the single form happened to be enough; on POSIX
 * `provisionWorktree` calls `symlinkSync(from, to, "dir")` and git stages a
 * mode-120000 blob whose CONTENT is the absolute path of the user's real
 * `.godot`, which `land`'s `git merge --squash` then writes into their repo.
 * The bare form also excludes a plain FILE named `target` or `.godot`, which
 * is intended: nothing named after a build cache is source.
 *
 * @returns {string[]}
 */
export function artifactExcludePathspecs() {
  return [...GENERATED_ARTIFACT_PATTERNS, ...NEVER_COMMIT_PATTERNS].flatMap((pattern) => {
    const bare = pattern.replace(/\/$/, "");
    return pattern.endsWith("/")
      ? [`:(exclude,glob)**/${bare}`, `:(exclude,glob)**/${bare}/**`]
      : [`:(exclude,glob)**/${pattern}`];
  });
}

/**
 * Compact, single-line description of a failed git invocation.
 *
 * `formatCommandFailure` echoes the whole argv, and the argv here is forty-odd
 * exclude pathspecs — unreadable in a status line. Only the exit status and
 * the first few lines of git's own diagnostic carry information.
 *
 * @param {string} operation
 * @param {{status: number|null, signal: string|null, stdout: string, stderr: string}} result
 */
function formatGitFailure(operation, result) {
  const code = result.signal ? `signal=${result.signal}` : `exit=${result.status}`;
  const detail = String(result.stderr || result.stdout || "")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .slice(0, 3)
    .join("; ");
  return detail ? `git ${operation} failed (${code}): ${detail}` : `git ${operation} failed (${code})`;
}

/**
 * Exclude pathspecs for every symlink/junction sitting at the worktree root.
 *
 * `provisionWorktree` may still junction *read-mostly* directories (e.g.
 * `vendor/`) out of the user's real repository. Live-state dirs are private
 * now, but any remaining reparse point at the worktree root must not be
 * staged: without this, `git add -A -- . <excludes>` stages the user's entire
 * real tree THROUGH the junction. `vendor/` is deliberately absent from
 * GENERATED_ARTIFACT_PATTERNS because Go projects commit it on purpose.
 *
 * So do it by observation instead of by name: whatever is a link is not this
 * run's work. Node reports Windows junctions as symbolic links via
 * lstat/Dirent — `unlinkReparsePointsSync` above already depends on exactly
 * that — so one check covers both platforms. Both the bare and the recursive
 * form are emitted for the same reason `artifactExcludePathspecs` emits both:
 * on POSIX the link itself is a stageable mode-120000 blob.
 *
 * Scan the worktree for symlink/junction reparse points (root and nested).
 *
 * C18: `planWorktreeLinks` also creates share junctions under nested project
 * dirs (e.g. `game/vendor`). Root-only scanning left those walkable by
 * `git add -A` on Windows.
 *
 * A link git ALREADY ignores gets no pathspec at all, and that omission is the
 * whole point rather than an optimisation. `git add` fails outright — exit 1,
 * `The following paths are ignored by one of your .gitignore files: target` —
 * when a pathspec explicitly names an ignored path, even an `:(exclude)` one.
 * The provisioned links are exactly the directories a project gitignores
 * (`target`, `node_modules`, `.venv`), so naming them broke the commit for
 * every isolated run that had anything to stage. Measured: a Rust run that
 * produced 22 files of real work committed nothing and reported
 * `changed files: none`, because `add` aborted on a `:(exclude,glob)target`
 * pathspec for a link that `.gitignore` already covered. An ignored path cannot
 * be staged, so it never needed an exclude in the first place.
 *
 * @param {string} worktreePath
 * @param {{ maxDepth?: number }} [options]
 * @returns {string[]}
 */
export function collectWorktreeReparsePaths(worktreePath, options = {}) {
  const maxDepth = Number.isFinite(Number(options.maxDepth)) ? Number(options.maxDepth) : 8;
  const found = [];

  function walk(dir, rel, depth) {
    if (depth > maxDepth) {
      return;
    }
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const name = entry.name;
      if (name === ".git") {
        continue;
      }
      const childRel = rel ? `${rel}/${name}` : name;
      const full = path.join(dir, name);
      if (entry.isSymbolicLink()) {
        found.push(childRel.replace(/\\/g, "/"));
        // Do not walk into junctions — that would traverse the main tree.
        continue;
      }
      if (entry.isDirectory()) {
        walk(full, childRel, depth + 1);
      }
    }
  }

  walk(worktreePath, "", 0);
  return found;
}

/**
 * @param {string} worktreePath
 * @returns {string[]}
 */
export function linkExcludePathspecs(worktreePath) {
  const links = collectWorktreeReparsePaths(worktreePath);
  if (links.length === 0) {
    return [];
  }

  // One `check-ignore` for the whole set: it exits 1 when NOTHING matches, which
  // is not an error here, and prints one line per ignored path when some do.
  // Cap argv size on huge monorepos by batching.
  const ignored = new Set();
  const batchSize = 64;
  for (let i = 0; i < links.length; i += batchSize) {
    const batch = links.slice(i, i + batchSize);
    const check = git(worktreePath, ["check-ignore", "--", ...batch]);
    if (check.status === 0) {
      for (const line of String(check.stdout ?? "").split(/\r?\n/)) {
        const name = line.trim().replace(/\\/g, "/");
        if (name) {
          ignored.add(name);
        }
      }
    }
  }

  return links
    .filter((name) => !ignored.has(name))
    .flatMap((name) => [`:(exclude,glob)${name}`, `:(exclude,glob)${name}/**`]);
}

/**
 * Commit any uncommitted agent changes inside the worktree.
 *
 * Never throws for a git-level failure. A run whose commit fails still
 * produced a transcript, a thread id, usage numbers and verify results, and
 * the agent's work is still on disk in the worktree — flattening all of that
 * into an exception loses the run to report the loss.
 *
 * @param {string} worktreePath
 * @param {string} [message]
 * @returns {{committed: boolean, sha: string, error?: string}}
 */
export function commitWorktreeChanges(worktreePath, message = "grok agent changes") {
  // Unchecked: a throw here would discard an otherwise complete run and
  // contradict the no-throw contract above. A failed rev-parse yields sha:null.
  const headSha = () => {
    const result = git(worktreePath, ["rev-parse", "HEAD"]);
    if (result.status !== 0 || result.error) {
      return null;
    }
    const sha = String(result.stdout ?? "").trim();
    return sha || null;
  };

  const status = git(worktreePath, ["status", "--porcelain"]);
  // A non-zero status is NOT a clean tree. Conflating the two made a locked
  // index (or any status failure) look like "nothing to commit", which the
  // bridge then recorded as completed-noop / nothing-written while real work
  // sat uncommitted in the worktree.
  if (status.status !== 0 || status.error) {
    return { committed: false, sha: headSha(), error: formatGitFailure("status", status) };
  }
  if (!status.stdout.trim()) {
    return { committed: false, sha: headSha() };
  }

  // Stage everything except artifacts the verify command produced and anything
  // reachable only through a provisioned link.
  const staged = git(worktreePath, [
    "add",
    "-A",
    "--",
    ".",
    ...artifactExcludePathspecs(),
    ...linkExcludePathspecs(worktreePath)
  ]);
  // Nothing left after excluding artifacts means the run produced only build
  // output — there is no agent work to commit. Read the index BEFORE deciding
  // what a non-zero `add` meant: git stages what it can and then complains, so
  // "add failed" and "nothing was staged" are independent facts.
  const stagedNames = git(worktreePath, ["diff", "--cached", "--name-only"]);
  const stagedSomething = stagedNames.status === 0 && Boolean(stagedNames.stdout.trim());

  if (staged.status !== 0 && !stagedSomething) {
    // Deliberately NO fallback to a bare `add -A`: that stages the caches and
    // the linked-in real directories this pathspec list exists to keep out,
    // and `land` then squash-merges them into the user's repository. A `:!`
    // retry is not an older-git fallback either — `:!` is just shorthand for
    // `:(exclude)` and needs the same pathspec magic. Report and stop.
    return { committed: false, sha: headSha(), error: formatGitFailure("add", staged) };
  }

  if (staged.status !== 0) {
    // The index received the run's work and git still exited non-zero. That is
    // the shape of a complaint about a path it declined to stage — an ignored
    // one, most often — not a failure to stage the work. Throwing the whole
    // commit away here cost a real run: 22 files of finished work sat
    // uncommitted in a worktree and the run reported `changed files: none`,
    // because `add` had aborted over one gitignored link. Commit what is in the
    // index; linkExcludePathspecs no longer names ignored paths, so reaching
    // this branch at all should now be rare.
    process.stderr.write(
      `Warning: ${formatGitFailure("add", staged)}; the index received this run's work, committing it anyway.\n`
    );
  }

  if (!stagedSomething) {
    return { committed: false, sha: headSha() };
  }

  // The commit can fail as readily as the add — a locked .blend on Windows, a
  // failing pre-commit hook, an unset user.email — so it gets the same
  // treatment rather than a throw.
  const commit = git(worktreePath, ["commit", "-m", message]);
  if (commit.status !== 0) {
    return { committed: false, sha: headSha(), error: formatGitFailure("commit", commit) };
  }

  return { committed: true, sha: headSha() };
}

/**
 * Hard caps on the changed-files manifest.
 *
 * Two of them, because either one alone is insufficient. A Godot re-import or a
 * Blender asset pass can touch thousands of files (entry cap), and a single
 * Blender path — nested collections, long asset names — runs well past 200
 * characters, so a few hundred of those alone would be a wall of text in a job
 * record and in the terminal (byte cap).
 */
export const CHANGED_FILES_MAX_ENTRIES = 200;
export const CHANGED_FILES_MAX_BYTES = 32 * 1024;

/**
 * Apply both caps to a list of `<status>\t<path>` manifest entries.
 *
 * @param {string[]} all
 * @param {{maxEntries?: number, maxBytes?: number}} [options]
 * @returns {{entries: string[], total: number, truncated: boolean}}
 */
export function capChangedFiles(all, options = {}) {
  const maxEntries = Number.isFinite(options.maxEntries) ? options.maxEntries : CHANGED_FILES_MAX_ENTRIES;
  const maxBytes = Number.isFinite(options.maxBytes) ? options.maxBytes : CHANGED_FILES_MAX_BYTES;
  const entries = [];
  let bytes = 0;
  for (const entry of all) {
    if (entries.length >= maxEntries) {
      break;
    }
    bytes += Buffer.byteLength(entry, "utf8") + 1;
    if (bytes > maxBytes && entries.length > 0) {
      break;
    }
    entries.push(entry);
  }
  return { entries, total: all.length, truncated: entries.length < all.length };
}

/**
 * What the agent's commit actually changed, as a `<status>\t<path>` manifest.
 *
 * For a Godot or Blender run the artifact IS the deliverable, and until now the
 * only thing a write run reported was "here is a worktree path, go look" — the
 * user had no way to tell a run that rebuilt a scene from one that produced
 * nothing but an import cache. The commit has already filtered the caches out
 * (`commitWorktreeChanges`), so this range is exactly the agent's work.
 *
 * `--no-renames` on purpose: a rename otherwise prints `R100\told\tnew`, a
 * three-field line in a two-field list. Splitting it into a D and an A is
 * marginally noisier and unambiguously parseable.
 *
 * Best-effort — a failure here costs the manifest, never the run.
 *
 * @param {string} worktreePath
 * @param {string} baseSha
 * @param {string} headSha
 * @param {{maxEntries?: number, maxBytes?: number}} [options]
 * @returns {{entries: string[], total: number, truncated: boolean, error?: string}}
 */
/**
 * How many `.tscn`/`.tres` files get an ext_resource annotation in the
 * changed-files manifest. Bounded deliberately: each annotation may show
 * git show of two blob versions, and a bulk scene rewrite is not helped by
 * a thousand-line digression inside the run record.
 */
const SCENE_ANNOTATION_MAX = 12;

/**
 * Annotate modified/added scene and resource files with a cheap ext_resource
 * summary. Keeps the existing caps; annotations replace the bare path line
 * rather than adding a second entry, so the entry count does not grow.
 *
 * @param {string} worktreePath
 * @param {string} baseSha
 * @param {string[]} entries
 * @param {{ gitImpl?: typeof git }} [options]
 * @returns {string[]}
 */
export function annotateGodotChangedFiles(worktreePath, baseSha, entries, options = {}) {
  const gitImpl = options.gitImpl ?? git;
  if (!Array.isArray(entries) || entries.length === 0) {
    return entries ?? [];
  }

  let annotated = 0;
  return entries.map((entry) => {
    if (annotated >= SCENE_ANNOTATION_MAX) {
      return entry;
    }
    const tab = entry.indexOf("\t");
    if (tab < 0) {
      return entry;
    }
    const status = entry.slice(0, tab).trim();
    const rel = entry.slice(tab + 1).trim();
    if (!/\.(tscn|tres)$/i.test(rel)) {
      return entry;
    }
    // Only M and A carry a useful before/after; D is just a deletion.
    if (status !== "M" && status !== "A" && !/^M/.test(status)) {
      return entry;
    }

    let beforeText = "";
    let afterText = "";
    if (status === "M" || /^M/.test(status)) {
      const before = gitImpl(worktreePath, ["show", `${baseSha}:${rel}`], {
        maxBuffer: 512 * 1024
      });
      if (before.status === 0) {
        beforeText = String(before.stdout ?? "");
      }
    }
    const after = gitImpl(worktreePath, ["show", `HEAD:${rel}`], {
      maxBuffer: 512 * 1024
    });
    if (after.status === 0) {
      afterText = String(after.stdout ?? "");
    } else {
      // Fall back to the working tree file when HEAD:path fails (rare for a
      // just-committed tree, but cheap insurance).
      try {
        afterText = fs.readFileSync(path.join(worktreePath, rel), "utf8");
      } catch {
        return entry;
      }
    }

    const summary = summarizeSceneResourceChange(beforeText, afterText, rel);
    if (!summary) {
      // Still mark the kind so a reviewer sees "scene" rather than a bare path.
      const kind = /\.tscn$/i.test(rel) ? "scene" : "resource";
      annotated += 1;
      return `${status}\t${rel} (${kind} edit)`;
    }
    annotated += 1;
    return `${status}\t${rel} (${summary})`;
  });
}

export function listCommittedChanges(worktreePath, baseSha, headSha, options = {}) {
  if (!baseSha || !headSha || baseSha === headSha) {
    return { entries: [], total: 0, truncated: false };
  }
  const diff = git(
    worktreePath,
    ["diff", "--name-status", "--no-renames", `${baseSha}..${headSha}`],
    // Explicit because runCommand restores spawnSync's 1 MiB default when the
    // caller supplies nothing, and one line per changed file across a large
    // asset import can exceed it.
    { maxBuffer: 8 * 1024 * 1024 }
  );
  if (diff.status !== 0 || diff.error) {
    return { entries: [], total: 0, truncated: false, error: formatGitFailure("diff", diff) };
  }
  const all = String(diff.stdout ?? "")
    .split(/\r?\n/)
    .map((line) => line.trimEnd())
    .filter(Boolean);
  // Annotate before capping so a scene rewrite near the end of a large change
  // set still has a chance to explain itself within the byte budget.
  const annotated =
    options.annotateGodot === false
      ? all
      : annotateGodotChangedFiles(worktreePath, baseSha, all, options);
  return capChangedFiles(annotated, options);
}
