/**
 * Git worktree lifecycle for isolated agent runs.
 */

import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import process from "node:process";

import { ensureGitRepository, git, gitChecked } from "./git.mjs";

/**
 * Artifacts produced by RUNNING a project, never by editing it.
 *
 * Deliberately excludes anything ambiguous: `dist/` and `build/` are committed
 * deliberately by plenty of projects, so they are not listed. Same reasoning
 * keeps Godot's `android/build/` out - the installed Android build template is
 * routinely hand-customized, so it is source in every project that has it.
 */
const GENERATED_ARTIFACT_PATTERNS = Object.freeze([
  "__pycache__/",
  "*.py[cod]",
  ".pytest_cache/",
  ".mypy_cache/",
  ".ruff_cache/",
  ".tox/",
  "__pypackages__/",
  "*.egg-info/",
  "node_modules/",
  "target/",
  "obj/",
  ".gradle/",
  "*.tsbuildinfo",
  // Godot: .import is Godot 3's asset import CACHE DIRECTORY; .godot is Godot
  // 4's. Neither is source - both are regenerated from project assets.
  //
  // These are DIRECTORY patterns on purpose. Never "harmonize" `.import/` into
  // `*.import`, and never add `*.uid`: `icon.png.import` and `player.gd.uid`
  // are SOURCE. They carry the `uid://...` identifier that every `.tscn`/
  // `.tres` `ext_resource uid=` line resolves through, so dropping them from a
  // commit breaks resource references across the whole project. Godot 4.4 does
  // regenerate a missing `.uid` - with a NEW RANDOM uid - which is exactly why
  // "it regenerates" is the wrong reason to exclude it.
  ".import/",
  ".godot/",
  // Godot 3 emitted C# build output into `.mono/` at the project root; Godot
  // 4's equivalent lives under `.godot/mono` and is already covered above.
  ".mono/",
  // Blender: incremental save backups. `scene.blend1` is the previous save,
  // and Save Versions goes up to 32, so both a one- and two-digit form are
  // needed. `.blend@` is NOT a backup - it is the transient write target
  // Blender renames over the real file on a successful save, so it only ever
  // survives a crashed or interrupted save. Deliberately does NOT list
  // `*.blend` itself: the scene file is the source of a Blender project.
  "*.blend[0-9]",
  "*.blend[0-9][0-9]",
  "*.blend@",
  "*.blend[0-9]@",
  // JS/web framework build caches - regenerated by the framework's own
  // dev/build command, never meant to be committed. Unlike a generic
  // dist/build folder name (which some projects DO commit deliberately, so
  // is intentionally not listed here), these framework-specific directory
  // names are unambiguous build output in every project that has them.
  ".next/",
  ".nuxt/",
  ".svelte-kit/",
  ".turbo/",
  ".parcel-cache/"
]);

/**
 * Machine-local secrets that must never reach a commit, even though they are
 * not "generated artifacts" in the sense above.
 *
 * Kept as a separate constant precisely so the next reader does not "clean up"
 * an odd credentials entry sitting among build caches.
 *
 * `export_credentials.cfg` is Godot 4.2+: the editor moved keystore passwords
 * and notarization credentials out of `export_presets.cfg` into this sibling
 * file, which is machine-local by design. A headless `--export-release` run
 * can generate it inside the worktree, so it has to be excluded even though
 * `git worktree add` would never have materialised one.
 *
 * `export_presets.cfg` itself is deliberately NOT listed: it is normal,
 * already-tracked project source in the user's repository.
 */
const NEVER_COMMIT_PATTERNS = Object.freeze(["export_credentials.cfg"]);

/**
 * @param {string} runId
 * @param {{ dataDir?: string, env?: NodeJS.ProcessEnv }} [options]
 */
export function resolveWorktreePath(runId, options = {}) {
  const env = options.env ?? process.env;
  if (options.dataDir) {
    return path.join(options.dataDir, "worktrees", runId);
  }
  if (env.CLAUDE_PLUGIN_DATA) {
    return path.join(env.CLAUDE_PLUGIN_DATA, "worktrees", runId);
  }
  return path.join(os.tmpdir(), "grok-cc-worktrees", runId);
}

/**
 * Create a worktree for a run.
 *
 * @param {object} options
 * @param {string} options.cwd - source repository cwd
 * @param {string} options.runId
 * @param {string} [options.baseRef] - defaults to HEAD
 * @param {string} [options.dataDir]
 * @param {NodeJS.ProcessEnv} [options.env]
 */
export function createWorktree({ cwd, runId, baseRef = "HEAD", dataDir, env }) {
  const repoRoot = ensureGitRepository(cwd);
  if (!runId) {
    throw new Error("runId is required");
  }

  const branchName = `grok-build/${runId}`;
  const worktreePath = resolveWorktreePath(runId, { dataDir, env });
  const baseSha = gitChecked(repoRoot, ["rev-parse", baseRef]).stdout.trim();

  fs.mkdirSync(path.dirname(worktreePath), { recursive: true });

  if (fs.existsSync(worktreePath)) {
    throw new Error(`Worktree path already exists: ${worktreePath}`);
  }

  const result = git(repoRoot, ["worktree", "add", "-b", branchName, worktreePath, baseSha]);
  if (result.status !== 0) {
    // Branch may already exist from a crashed run — try without -b
    const retry = git(repoRoot, ["worktree", "add", worktreePath, branchName]);
    if (retry.status !== 0) {
      const combined = [result.stderr, result.stdout, retry.stderr, retry.stdout]
        .map((s) => (s || "").trim())
        .filter(Boolean)
        .join("\n");
      throw new Error(`Failed to create worktree: ${combined}`);
    }
  }

  return {
    worktreePath,
    branchName,
    baseSha,
    baseRef,
    repoRoot,
    runId
  };
}

/**
 * Remove a worktree and optionally its branch.
 *
 * @param {object} options
 * @param {string} options.repoRoot
 * @param {string} options.worktreePath
 * @param {string} [options.branchName]
 * @param {boolean} [options.deleteBranch]
 */
/**
 * Remove every symlink/junction inside a worktree, WITHOUT descending into one.
 *
 * Confirmed empirically: `git worktree remove --force` on Windows follows a
 * junction it encounters while deleting the tree and destroys the CONTENTS of
 * whatever it points at. lib/provision.mjs links node_modules/.venv/target etc.
 * straight from the user's real repository, so tearing down a worktree that
 * still contains those links wiped the real directories in a reproduction
 * (empty node_modules/ survived; node_modules/pkg/marker.txt inside it did not).
 *
 * The only safe order is: unlink every reparse point first, so by the time git
 * (or the fs.rmSync fallback below) walks the tree, there is nothing left to
 * follow through. This must run before ANY removal path, not only the fallback.
 */
function unlinkReparsePointsSync(root) {
  let entries;
  try {
    entries = fs.readdirSync(root, { withFileTypes: true });
  } catch {
    return;
  }

  for (const entry of entries) {
    const entryPath = path.join(root, entry.name);
    if (entry.isSymbolicLink()) {
      // Covers POSIX symlinks and Windows junctions (Node reports junctions as
      // symbolic links via lstat/Dirent). rmdir removes a Windows junction or a
      // directory-targeted symlink without touching its target; unlink handles
      // a file-targeted symlink. Never rmSync/recursive here — that is exactly
      // the operation this function exists to protect against.
      try {
        fs.rmdirSync(entryPath);
      } catch {
        try {
          fs.unlinkSync(entryPath);
        } catch {
          // Leaving an un-removable link is safer than risking a recursive
          // delete following it later; the outer removal may then fail loudly
          // instead of silently destroying the link target.
        }
      }
      continue;
    }
    if (entry.isDirectory()) {
      unlinkReparsePointsSync(entryPath);
    }
  }
}

export function removeWorktree({ repoRoot, worktreePath, branchName, deleteBranch = true }) {
  if (worktreePath && fs.existsSync(worktreePath)) {
    unlinkReparsePointsSync(worktreePath);
    const result = git(repoRoot, ["worktree", "remove", "--force", worktreePath]);
    if (result.status !== 0) {
      try {
        fs.rmSync(worktreePath, { recursive: true, force: true });
      } catch {
        // best-effort
      }
      git(repoRoot, ["worktree", "prune"]);
    }
  } else {
    git(repoRoot, ["worktree", "prune"]);
  }

  if (deleteBranch && branchName) {
    git(repoRoot, ["branch", "-D", branchName]);
  }

  const reasons = [];
  if (worktreePath && fs.existsSync(worktreePath)) {
    reasons.push("worktree directory still exists after removal attempt");
  }
  if (deleteBranch && branchName) {
    const branchCheck = git(repoRoot, ["rev-parse", "--verify", branchName]);
    if (branchCheck.status === 0) {
      reasons.push(`branch ${branchName} still exists after delete attempt`);
    }
  }

  if (reasons.length > 0) {
    return {
      removed: false,
      worktreePath,
      branchName,
      reason: reasons.join("; ")
    };
  }

  return { removed: true, worktreePath, branchName };
}

/**
 * Pathspecs that stage everything except generated artifacts.
 *
 * Pathspec magic is used instead of info/exclude: in a linked worktree git
 * reads excludes from the common git dir, so per-worktree exclude files are
 * ignored. Pathspecs apply to one `git add` and write nothing into repo metadata.
 *
 * A directory pattern needs BOTH forms: the bare one and the recursive one.
 * The recursive form requires a path component AFTER `.godot`, so it never
 * matches an index entry whose path is exactly `.godot` - which is what git
 * records for that entry when it is a symlink rather than a directory. On
 * win32 the provisioned `.godot` is a junction and
 * git sees a directory, so the single form happened to be enough; on POSIX
 * `provisionWorktree` calls `symlinkSync(from, to, "dir")` and git stages a
 * mode-120000 blob whose CONTENT is the absolute path of the user's real
 * `.godot`, which `land`'s `git merge --squash` then writes into their repo.
 * The bare form also excludes a plain FILE named `target` or `.godot`, which
 * is intended: nothing named after a build cache is source.
 *
 * @returns {string[]}
 */
export function artifactExcludePathspecs() {
  return [...GENERATED_ARTIFACT_PATTERNS, ...NEVER_COMMIT_PATTERNS].flatMap((pattern) => {
    const bare = pattern.replace(/\/$/, "");
    return pattern.endsWith("/")
      ? [`:(exclude,glob)**/${bare}`, `:(exclude,glob)**/${bare}/**`]
      : [`:(exclude,glob)**/${pattern}`];
  });
}

/**
 * Compact, single-line description of a failed git invocation.
 *
 * `formatCommandFailure` echoes the whole argv, and the argv here is forty-odd
 * exclude pathspecs — unreadable in a status line. Only the exit status and
 * the first few lines of git's own diagnostic carry information.
 *
 * @param {string} operation
 * @param {{status: number|null, signal: string|null, stdout: string, stderr: string}} result
 */
function formatGitFailure(operation, result) {
  const code = result.signal ? `signal=${result.signal}` : `exit=${result.status}`;
  const detail = String(result.stderr || result.stdout || "")
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .slice(0, 3)
    .join("; ");
  return detail ? `git ${operation} failed (${code}): ${detail}` : `git ${operation} failed (${code})`;
}

/**
 * Exclude pathspecs for every symlink/junction sitting at the worktree root.
 *
 * `provisionWorktree` links heavyweight directories straight out of the user's
 * real repository (`PROVISION_LINK_DIRS`), and three of them — `.venv`, `venv`
 * and `vendor` — are deliberately absent from GENERATED_ARTIFACT_PATTERNS,
 * because Go projects commit `vendor/` on purpose and no name-based list can
 * know which is which. Without this, `git add -A -- . <excludes>` stages the
 * user's entire real `.venv` THROUGH the junction on every isolated Python run.
 *
 * So do it by observation instead of by name: whatever is a link is not this
 * run's work. Node reports Windows junctions as symbolic links via
 * lstat/Dirent — `unlinkReparsePointsSync` above already depends on exactly
 * that — so one check covers both platforms. Both the bare and the recursive
 * form are emitted for the same reason `artifactExcludePathspecs` emits both:
 * on POSIX the link itself is a stageable mode-120000 blob.
 *
 * Only the worktree root is scanned, because that is the only place
 * `planWorktreeLinks` ever creates a link.
 *
 * @param {string} worktreePath
 * @returns {string[]}
 */
function linkExcludePathspecs(worktreePath) {
  let entries;
  try {
    entries = fs.readdirSync(worktreePath, { withFileTypes: true });
  } catch {
    // A worktree we cannot read is a problem the `git add` below will report
    // far more usefully than a thrown ENOENT from a pathspec helper.
    return [];
  }

  return entries
    .filter((entry) => entry.isSymbolicLink())
    .flatMap((entry) => [
      `:(exclude,glob)${entry.name}`,
      `:(exclude,glob)${entry.name}/**`
    ]);
}

/**
 * Commit any uncommitted agent changes inside the worktree.
 *
 * Never throws for a git-level failure. A run whose commit fails still
 * produced a transcript, a thread id, usage numbers and verify results, and
 * the agent's work is still on disk in the worktree — flattening all of that
 * into an exception loses the run to report the loss.
 *
 * @param {string} worktreePath
 * @param {string} [message]
 * @returns {{committed: boolean, sha: string, error?: string}}
 */
export function commitWorktreeChanges(worktreePath, message = "grok agent changes") {
  const headSha = () => gitChecked(worktreePath, ["rev-parse", "HEAD"]).stdout.trim();

  const status = git(worktreePath, ["status", "--porcelain"]);
  if (status.status !== 0 || !status.stdout.trim()) {
    return { committed: false, sha: headSha() };
  }

  // Stage everything except artifacts the verify command produced and anything
  // reachable only through a provisioned link.
  const staged = git(worktreePath, [
    "add",
    "-A",
    "--",
    ".",
    ...artifactExcludePathspecs(),
    ...linkExcludePathspecs(worktreePath)
  ]);
  if (staged.status !== 0) {
    // Deliberately NO fallback to a bare `add -A`: that stages the caches and
    // the linked-in real directories this pathspec list exists to keep out,
    // and `land` then squash-merges them into the user's repository. A `:!`
    // retry is not an older-git fallback either — `:!` is just shorthand for
    // `:(exclude)` and needs the same pathspec magic. Report and stop.
    return { committed: false, sha: headSha(), error: formatGitFailure("add", staged) };
  }

  // Nothing left after excluding artifacts means the run produced only build
  // output — there is no agent work to commit.
  const stagedNames = git(worktreePath, ["diff", "--cached", "--name-only"]);
  if (stagedNames.status === 0 && !stagedNames.stdout.trim()) {
    return { committed: false, sha: headSha() };
  }

  // The commit can fail as readily as the add — a locked .blend on Windows, a
  // failing pre-commit hook, an unset user.email — so it gets the same
  // treatment rather than a throw.
  const commit = git(worktreePath, ["commit", "-m", message]);
  if (commit.status !== 0) {
    return { committed: false, sha: headSha(), error: formatGitFailure("commit", commit) };
  }

  return { committed: true, sha: headSha() };
}
